### ISSUE TITLE
Can not create DDL for synonym.

### ISSUE THREAD

**Issue by gpaulissen** [paulissoft/oracle-tools#103]
This synonym is not created:

```
CREATE OR REPLACE SYNONYM "ORACLE_TOOLS"."Nieuwe bestellingen" FOR "ORACLE_TOOLS"."BCP_LEASEPLAN_ENERGY_IMPORT";
```

This is the POM:

```
    <db.object.names.include>1</db.object.names.include> <!-- 0: exclude db.object.names; 1: include only db.object.names; empty: all DB objects -->
    <db.object.names>BCP_LEASEPLAN_ENERGY_IMPORT,Sheet1,Nieuwe bestellingen</db.object.names>
```

**Comment by RinsuAnn** [comment]
Kindly check the table "ORACLE_TOOLS"."BCP_LEASEPLAN_ENERGY_IMPORT";" has records, if so truncate and retry

**Comment by paulissoft** [comment]
The cause of the problem was the whitespace trimming in Ant script `db/src/scripts/generate_ddl.xml`, thus changing "Nieuwe bestellingen" into "Nieuwebestellingen". Whitespace trimming is now only done by the database.
