### ISSUE TITLE
The smart pool data source statistics class raises a null pointer exception due to not checking the SQL state of an exception.

### ISSUE THREAD

**Issue by bluecurrent-paulissoft** [paulissoft/oracle-tools#168]
A SQLException may return null for [getSQLState](https://docs.oracle.com/javase/8/docs/api/java/sql/SQLException.html#getSQLState) and since that value is put into Properties, a NullPointerException was raised (property values can not be null).

**Comment by gpaulissen** [comment]
Release 3.3.2
