### ISSUE TITLE
It should be possible to exclude (temporary) database jobs while generating DDL.

### ISSUE THREAD

**Issue by gpaulissen** [paulissoft/oracle-tools#22]
On a client site temporary database jobs (dbms_scheduler) are run while DDL generation is running. This leads to object not found errors since the (temorary) PROCOBJ objects are created and destroyed a little later.

**Comment by gpaulissen** [comment]
There is a facility to add a filter for object type. Currently this allows only for filtering on an object type (inclusive). This should turn into all but this object type. The easiest way to do this is to add a negation mark (!) in front of the parameter.

**Comment by paulissoft** [comment]
You can now exclude objects, see [It must be possible to use a schema object id for specifying the object to (NOT) generate DDL for.](https://github.com/paulissoft/oracle-tools/issues/89).
