### ISSUE TITLE
Import of APEX application (with translated app) is successful, but returns with error

### ISSUE THREAD

**Issue by gleeuwen** [paulissoft/oracle-tools#24]
After exporting an Apex app and install it in another environment. The following error occurred:

INFO]      [java] ... elapsed: 121,54 sec
[INFO]      [java] 
[INFO]      [java] ...done
[INFO]      [java] @@ publish_application.sql
[INFO]      [java] (publish_application.sql)
[INFO]      [java] 
[INFO]      [java] Session altered.
[INFO]      [java] 
[INFO]      [java] workspace id    : 9503542584009799
[INFO]      [java] application id  : 116
[INFO]      [java] *** update_language_mapping ***
[INFO]      [java] primary_application_id  : 116
[INFO]      [java] translated_app_language : nl
[INFO]      [java] new_trans_application_id: 11601
[INFO]      [java] ORA-01722: invalid number
[INFO]      [java] 
[INFO]      [java] 
[INFO]      [java] Error starting at line : 10 File @ /Users/gleeuwen/zakelijk/bluecurrent/git/oracle-tools/apex/src/scripts/publish_application.sql
[INFO]      [java] In command -
[INFO]      [java] declare
[INFO]      [java]   cursor c_translations
[INFO]      [java]   ( b_primary_application_id in apex_application_trans_map.primary_application_id%type
[INFO]      [java]   ) is
[INFO]      [java]     select  t.primary_application_id
[INFO]      [java]     ,       t.translated_app_language
[INFO]      [java]     ,       t.translated_application_id
[INFO]      [java]     ,       t.primary_application_id * 100
[INFO]      [java]             + (row_number() over (partition by t.primary_application_id order by t.translated_app_language)) as new_trans_application_id
[INFO]      [java]     from    apex_application_trans_map t
[INFO]      [java]     where   t.primary_application_id = b_primary_application_id
[INFO]      [java]     order by
[INFO]      [java]             t.primary_application_id
[INFO]      [java]     ,       t.translated_app_language;  
[INFO]      [java] begin
[INFO]      [java]   dbms_output.put_line('workspace id    : ' || wwv_flow_application_install.get_workspace_id);
[INFO]      [java]   dbms_output.put_line('application id  : ' || wwv_flow_application_install.get_application_id);
[INFO]      [java] 
[INFO]      [java]   apex_util.set_security_group_id(wwv_flow_application_install.get_workspace_id);
[INFO]      [java] 
[INFO]      [java]   dbms_output.put_line('*** update_language_mapping ***');
[INFO]      [java] 
[INFO]      [java]   for r in c_translations(wwv_flow_application_install.get_application_id)
[INFO]      [java]   loop    
[INFO]      [java]     dbms_output.put_line('primary_application_id  : ' || r.primary_application_id);
[INFO]      [java]     dbms_output.put_line('translated_app_language : ' || r.translated_app_language);
[INFO]      [java]     dbms_output.put_line('new_trans_application_id: ' || r.new_trans_application_id);
[INFO]      [java] 
[INFO]      [java]     if r.translated_application_id != r.new_trans_application_id
[INFO]      [java]     then
[INFO]      [java]       apex_lang.update_language_mapping
[INFO]      [java]       ( p_application_id => r.primary_application_id
[INFO]      [java]       , p_language => r.translated_app_language
[INFO]      [java]       , p_new_trans_application_id => r.new_trans_application_id
[INFO]      [java]       );
[INFO]      [java]     end if;
[INFO]      [java]   end loop;
[INFO]      [java] 
[INFO]      [java]   commit;
[INFO]      [java] 
[INFO]      [java]   dbms_output.put_line('*** publish application ***');
[INFO]      [java] 
[INFO]      [java]   for r in c_translations(wwv_flow_application_install.get_application_id)
[INFO]      [java]   loop
[INFO]      [java]     dbms_output.put_line('primary_application_id  : ' || r.primary_application_id);
[INFO]      [java]     dbms_output.put_line('translated_app_language : ' || r.translated_app_language);
[INFO]      [java]     dbms_output.put_line('new_trans_application_id: ' || r.new_trans_application_id);
[INFO]      [java] 
[INFO]      [java]     apex_lang.publish_application
[INFO]      [java]     ( p_application_id => r.primary_application_id
[INFO]      [java]     , p_language => r.translated_app_language
[INFO]      [java]     );
[INFO]      [java]   end loop;
[INFO]      [java] 
[INFO]      [java]   dbms_output.put_line(chr(10));
[INFO]      [java] 
[INFO]      [java]   commit;
[INFO]      [java] exception
[INFO]      [java]   when others
[INFO]      [java]   then
[INFO]      [java]     dbms_output.put_line(substr(sqlerrm, 1, 255));
[INFO]      [java]     raise;
[INFO]      [java] end;
[INFO]      [java] Error report -
[INFO]      [java] ORA-01722: invalid number
[INFO]      [java] ORA-06512: at line 62
[INFO]      [java] ORA-06512: at "APEX_210100.WWV_FLOW_LANG", line 2821
[INFO]      [java] ORA-06512: at "APEX_210100.HTMLDB_LANG", line 239
[INFO]      [java] ORA-06512: at line 31
[INFO]      [java] ORA-06512: at line 31
[INFO]      [java] 01722. 00000 -  "invalid number"
[INFO]      [java] *Cause:    The specified number was invalid.
[INFO]      [java] *Action:   Specify a valid number.
[ERROR]      [java] Java Result: 186
[WARNING]      [echo] (synchronize.xml.import)
[INFO] Executed tasks

**Comment by gpaulissen** [comment]
During the update_language_mapping / publish_application the translated application id number are mapped to a sequence starting at the primary application id * 1000 + 1. During this conversion the new number is calculated like this:

```
 * This code in wwv_flow_lang may cause an error:
 *
 * 2821     UPDATE WWV_FLOW_TRANSLATABLE_TEXT$
 * 2822        SET TRANSLATED_FLOW_ID = P_NEW_TRANS_APPLICATION_ID,
 * 2823            TRANSLATE_TO_ID = TO_NUMBER(TRANSLATE_FROM_ID || NVL(WWV_FLOW.G_NLS_DECIMAL_SEPARATOR,'.') || P_NEW_TRANS_APPLICATION_ID)
 * 2824      WHERE SECURITY_GROUP_ID = WWV_FLOW_SECURITY.G_SECURITY_GROUP_ID
 * 2825        AND TRANSLATED_FLOW_ID = L_OLD_TRANS_APPLICATION_ID
 * 2826        AND FLOW_ID = P_APPLICATION_ID;
```

The to_number() call implicitly needs to have the same decimal character as NVL(WWV_FLOW.G_NLS_DECIMAL_SEPARATOR,'.') and this may not be always the case. The solution is to set the nls_numeric_characters before doing the conversion.
