### ISSUE TITLE
The DDL subsystem generates a wrong install.sql for EPC

### ISSUE THREAD

**Issue by gpaulissen** [paulissoft/oracle-tools#6]
The type EPC_CLNT_OBJECT depends on STD_OBJECT but it will be created first since listed alphabetically.

**Comment by gpaulissen** [comment]
Maybe a good solution is to add a creation date order to the list of objects (USER_OBJECTS.CREATED). Change the type number (R__<nr>.[<OWNER>.]FUNCTION or <nr>.[<OWNER>.]TABLE) into a sequence number sorted by creation date.

**Comment by gpaulissen** [comment]
Or <type nr>-<created order nr>

**Comment by paulissoft** [comment]
A new interface version (pkg_ddl_util v5) has been introduced. The sequence number depends on file install_sequence.txt which initially depends on the object dependency order (the less dependencies the lower the sequence number). This file can be edited by the user.

**Comment by paulissoft** [comment]
The sequence number in that case is a 4 digit number (zero left padded).
