### ISSUE TITLE
It must be possible to use a schema object id for specifying the object to generating DDL for.

### ISSUE THREAD

**Issue by paulissoft** [paulissoft/oracle-tools#89]
The db.object.names property only allows for object names and sometimes it is necessary to add the object type for a more fine-grained selection.

The rules for filtering:
1. the combination of object type, object names and object names include will still be available;
2. next to that comes an include objects parameter and an exclude objects parameter, each a list (newline separated) of schema object id expressions having 10 cells separated by a colon (:) and each cell may be an exact value or a wildcard expression using O/S wildcards '*' and '?' (not SQL wildcards '%' and '_' because database object names often include the '_');
3. you can use both rules (you may use none).

**Comment by gpaulissen** [comment]
You can retrieve schema object info by:

1. `select value(t).schema_object_info() from table(oracle_tools.pkg_ddl_util.get_schema_object) t`
2. looking at lines in uninstall.sql like this `SQL statement 1 (REVOKE;;OBJECT_GRANT;;ORACLE_TOOLS;FUNCTION;F_GENERATE_DDL;;PUBLIC;EXECUTE;NO;2)`, take the expression inside the parentheses, remove the first and last column and replace ';' by ':'

Examples:
```
ORACLE_TOOLS:TABLE:DEMO_CONSTRAINT_LOOKUP:::::::
ORACLE_TOOLS:TABLE:DEMO_CUSTOMERS:::::::
ORACLE_TOOLS:TABLE:DEMO_ORDERS:::::::
ORACLE_TOOLS:TABLE:DEMO_ORDER_ITEMS:::::::
ORACLE_TOOLS:TABLE:DEMO_PRODUCT_INFO:::::::
ORACLE_TOOLS:TABLE:DEMO_STATES:::::::
ORACLE_TOOLS:TABLE:DEMO_TAGS:::::::
ORACLE_TOOLS:TABLE:DEMO_TAGS_SUM:::::::
ORACLE_TOOLS:TABLE:DEMO_TAGS_TYPE_SUM:::::::
ORACLE_TOOLS:TABLE:DEPT:::::::
```

**Comment by gpaulissen** [comment]
The expression has 9 separators and thus 10 columns.
