### ISSUE TITLE
Can not run unit test

### ISSUE THREAD

**Issue by paulissoft** [paulissoft/oracle-tools#9]
`[info] Writing report UT_DOCUMENTATION_REPORTER to Console
api_pkg
  ut_excel_date_number2date [,007 sec]
 
data_api_pkg
  ut_raise_error [,013 sec]
 
oracle_tools
  ui_apex_messages_pkg
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.201 s
[INFO] Finished at: 2021-08-24T14:23:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.utplsql:utplsql-maven-plugin:3.1.4:test (db-test) on project API: ORA-29471: DBMS_SQL access denied
`

**Comment by gpaulissen** [comment]
Solved by checking carefully the test CSV data for the end of line on Windows.
